import{CONNECTIONS,KNOTS,PRIORITIES}from'./data.js';import{recommendKnot}from'./logic.js';
const form=document.querySelector('#knotForm'),steps=[...document.querySelectorAll('.step')],error=document.querySelector('.form-error'),result=document.querySelector('#result'),progress=document.querySelector('.progress-bar'),progressLabel=document.querySelector('.progress-label'),storageKey='fishing-tools-knot-selector-v1';let state={},flow=[];
const selected=name=>form.querySelector(`input[name="${name}"]:checked`)?.value||'';
function sync(){state={connection:selected('connection')||state.connection,priority:selected('priority')||state.priority,peUse:selected('peUse')||state.peUse};localStorage.setItem(storageKey,JSON.stringify(state))}
function restore(){try{state=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{state={}};['connection','priority','peUse'].forEach(name=>{const el=form.querySelector(`input[name="${name}"][value="${state[name]}"]`);if(el)el.checked=true})}
function buildFlow(){flow=['connection','priority'];if(state.connection==='peLeader')flow.push('peUse')}
function show(index,focus=true){buildFlow();steps.forEach(s=>s.hidden=true);const name=flow[index],step=steps.find(s=>s.dataset.name===name);step.hidden=false;step.dataset.index=index;const next=step.querySelector('[data-next]');if(next)next.textContent=index===flow.length-1?'結果を見る':'次へ';progressLabel.textContent=`${index+1} / ${flow.length}`;progress.style.width=`${(index+1)/flow.length*100}%`;error.textContent='';if(focus)step.querySelector('legend')?.focus()}
function current(){return Number(steps.find(s=>!s.hidden)?.dataset.index||0)}
function validate(name){sync();if(name==='connection'&&!state.connection)return'何と何を結ぶか、1つ選んでください。';if(name==='priority'&&!state.priority)return'重視することを1つ選んでください。';if(name==='peUse'&&!state.peUse)return'ラインの使い方を1つ選んでください。';return''}
function metric(label,value){return`<div><span>${label}</span><strong>${value}</strong></div>`}
function renderAlternative(knot,i){const lead=i===0?'別の選び方':'もう1つの候補';return`<article class="alternative-card"><span>${lead}</span><h3>${knot.name}</h3><p>${knot.summary}</p><small>難易度：${knot.difficulty} ／ 強度：${knot.strength}</small><button type="button" class="future-link" disabled aria-label="${knot.name}の結び方は準備中">結び方は準備中</button></article>`}
function render(){sync();const r=recommendKnot(state);if(r.error){error.textContent=r.error;return}const k=r.primary;document.querySelector('#knotName').textContent=k.name;document.querySelector('#knotSummary').textContent=k.summary;document.querySelector('#whyText').textContent=r.reason;document.querySelector('#metrics').innerHTML=metric('難易度',k.difficulty)+metric('強度傾向',k.strength)+metric('結ぶ速さ',k.speed)+metric('向いている用途',k.uses);document.querySelector('#merits').innerHTML=k.merits.map(x=>`<li>${x}</li>`).join('');document.querySelector('#caution').textContent=k.caution;document.querySelector('#selectedConditions').innerHTML=`<span>${CONNECTIONS[state.connection].label}</span><b>＋</b><span>${PRIORITIES[state.priority]}を重視</span>${state.connection==='peLeader'?`<b>＋</b><span>${state.peUse==='light'?'細いPE・ライトゲーム':state.peUse==='heavy'?'太いPE・大型魚':'一般的なルアーフィッシング'}</span>`:''}`;document.querySelector('#alternatives').innerHTML=r.alternatives.map(renderAlternative).join('');result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'start'})}
form.addEventListener('change',sync);form.addEventListener('click',e=>{const next=e.target.closest('[data-next]'),back=e.target.closest('[data-back]');if(next){const step=next.closest('.step'),message=validate(step.dataset.name);if(message){error.textContent=message;return}sync();buildFlow();const index=current();if(index===flow.length-1)render();else show(index+1)}if(back)show(Math.max(0,current()-1))});document.querySelector('#retry').addEventListener('click',()=>{result.hidden=true;show(0);window.scrollTo({top:document.querySelector('.tool-panel').offsetTop-80,behavior:'smooth'})});restore();show(0,false);
