import{AMOUNT_HINTS,FISH_TYPES}from'./data.js';import{recommendCooler}from'./logic.js';
const form=document.querySelector('#coolerForm'),steps=[...document.querySelectorAll('.step')],progress=document.querySelector('.progress-bar'),progressLabel=document.querySelector('.progress-label'),error=document.querySelector('.form-error'),result=document.querySelector('#result'),storageKey='fishing-tools-cooler-navi-v1';let state={};
const selected=name=>form.querySelector(`input[name="${name}"]:checked`)?.value||'';
function sync(){state={fish:selected('fish')||state.fish,size:selected('size')||state.size,amount:selected('amount')||state.amount,load:selected('load')||state.load};localStorage.setItem(storageKey,JSON.stringify(state))}
function restore(){try{state=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{state={}};['fish','amount','load'].forEach(name=>{const el=form.querySelector(`input[name="${name}"][value="${state[name]}"]`);if(el)el.checked=true})}
function renderSizes(){const wrap=document.querySelector('#sizeChoices'),fish=FISH_TYPES[state.fish];wrap.innerHTML=fish?fish.sizes.map(([id,label])=>`<div class="choice"><input id="size-${id}" name="size" type="radio" value="${id}"${state.size===id?' checked':''}><label for="size-${id}"><strong>${label}</strong></label></div>`).join(''):'';if(fish&&!fish.sizes.some(([id])=>id===state.size))state.size=''}
function renderAmountHints(){const hints=AMOUNT_HINTS[state.fish]||AMOUNT_HINTS.other;document.querySelector('#amountFewHint').textContent=hints.few;document.querySelector('#amountNormalHint').textContent=hints.normal;document.querySelector('#amountManyHint').textContent=hints.many}
function show(index,focus=true){steps.forEach((s,i)=>s.hidden=i!==index);progressLabel.textContent=`${index+1} / ${steps.length}`;progress.style.width=`${(index+1)/steps.length*100}%`;error.textContent='';if(focus)steps[index].querySelector('legend')?.focus()}
function current(){return steps.findIndex(s=>!s.hidden)}
function validate(index){sync();if(index===0&&!state.fish)return'魚種を1つ選んでください。';if(index===1&&!state.size)return'想定する最大サイズを1つ選んでください。';if(index===2&&!state.amount)return'持ち帰る量を1つ選んでください。';if(index===3&&!state.load)return'魚以外に入れるものを1つ選んでください。';return''}
function render(){sync();const r=recommendCooler(state);if(r.error){error.textContent=r.error;return}document.querySelector('#capacity').textContent=r.label;document.querySelector('#capacitySub').textContent=r.large?'大型魚向けロングタイプを含めて比較':'容量帯の目安';document.querySelector('#storageStatus').textContent=r.storageStatus;document.querySelector('#innerText').textContent=r.innerText;document.querySelector('#reason').textContent=r.reason;document.querySelector('#iceText').textContent=r.ice;document.querySelector('#smaller').textContent=r.smaller;document.querySelector('#larger').textContent=r.larger;document.querySelector('#conditions').innerHTML=`<span>${r.fishLabel}</span><b>＋</b><span>${r.sizeLabel}</span><b>＋</b><span>${r.amountDisplay}</span><b>＋</b><span>${r.loadLabel}</span>`;document.querySelector('#largeAlert').hidden=!r.large;result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'start'})}
form.addEventListener('change',e=>{sync();if(e.target.name==='fish'){state.size='';renderSizes();renderAmountHints();sync()}});form.addEventListener('click',e=>{const next=e.target.closest('[data-next]'),back=e.target.closest('[data-back]');if(next){const index=current(),message=validate(index);if(message){error.textContent=message;return}if(index===0){renderSizes();renderAmountHints()}if(index===steps.length-1)render();else show(index+1)}if(back)show(Math.max(0,current()-1))});document.querySelector('#retry').addEventListener('click',()=>{result.hidden=true;show(0);window.scrollTo({top:document.querySelector('.tool-panel').offsetTop-80,behavior:'smooth'})});restore();renderSizes();renderAmountHints();show(0,false);
