import{AMOUNTS,AMOUNT_HINTS,CAPACITY_BANDS,FISH_TYPES,LOADS,LONG_BANDS,SIZE_ADJUST}from'./data.js';
const bands=[[6,10],[10,15],[15,20],[20,25],[24,32],[25,35],[30,35],[35,48],[48,60],[60,60]];const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function shiftBand(base,steps){const index=bands.findIndex(x=>x[0]===base[0]&&x[1]===base[1]);return index<0?base:bands[clamp(index+steps,0,bands.length-1)]}
const format=([min,max])=>min===max?`${min}L以上`:`${min}～${max}L`;
export function validateCoolerInput(input){if(!input.fish)return'魚種を1つ選んでください。';if(!FISH_TYPES[input.fish])return'魚種の選択を確認してください。';if(!input.size)return'想定する最大サイズを1つ選んでください。';if(!FISH_TYPES[input.fish].sizes.some(([id])=>id===input.size))return'魚のサイズを選び直してください。';if(!input.amount)return'持ち帰る量を1つ選んでください。';if(!AMOUNTS[input.amount])return'持ち帰る量を選び直してください。';if(!input.load)return'魚以外に入れるものを1つ選んでください。';if(!LOADS[input.load])return'荷物の選択を確認してください。';return''}
export function recommendCooler(input){const error=validateCoolerInput(input);if(error)return{error};const fish=FISH_TYPES[input.fish];let band,storageStatus='○',innerText='魚と氷・保冷剤を入れた状態を想定し、購入前に実際の内寸を確認してください。',large=false;
 if(fish.type==='long'){const row=LONG_BANDS[input.size];band=row[input.load];if(input.amount==='many')band=shiftBand(band,1);storageStatus=row.status;innerText=row.inner;large=input.size==='60to80'||input.size==='over80';}
 else{const family=fish.type==='other'?(input.size==='large'?'medium':'small'):fish.type;band=CAPACITY_BANDS[family][input.amount][input.load];const step=(SIZE_ADJUST[fish.type]||SIZE_ADJUST.other)[input.size]||0;band=shiftBand(band,step);if((fish.type==='medium'&&step>=1)||(fish.type==='other'&&input.size!=='small')){storageStatus='要確認';innerText='魚の形や長さによって収まり方が変わります。同じ容量でも内寸が異なるため、購入前に内寸長を確認してください。'}}
 const smaller=input.amount==='few'&&input.load==='fish'?'釣果が少なく、飲食物を別に持つなら下限側の容量を検討できます。':'持ち帰り量を減らし、飲食物を別にすると一段小さい容量を検討できます。';const larger=input.amount==='many'||input.load==='full'?'今回の条件では余裕側を優先してください。氷や保冷剤を入れる空間も残します。':'釣果が増える可能性がある場合や飲食物をまとめる場合は、一段大きい容量も比較してください。';
 const amountHint=AMOUNT_HINTS[input.fish][input.amount];return{band,label:format(band),fishLabel:fish.label,sizeLabel:fish.sizes.find(([id])=>id===input.size)[1],amountLabel:AMOUNTS[input.amount],amountHint,amountDisplay:`${AMOUNTS[input.amount]}（${amountHint}）`,loadLabel:LOADS[input.load],storageStatus,innerText,large,smaller,larger,reason:`${fish.label}のサイズ、持ち帰る量、魚以外の荷物を、メーカーの実製品にある容量帯へ当てはめた目安です。魚の体積計算は行っていません。`,ice:'魚だけで容量を使い切らず、氷や保冷剤を入れる余裕を確保してください。必要量は気温・釣行時間・保冷性能で変わるため、固定比率では計算していません。'}
}
