import{calculateBacking,calculateCapacity,roundMeters,validateNumber}from'./logic.js';
const form=document.querySelector('#reelForm');const steps=[...document.querySelectorAll('.step')];const progress=document.querySelector('.progress-bar');const progressLabel=document.querySelector('.progress-label');const error=document.querySelector('.form-error');const result=document.querySelector('#result');const storageKey='fishing-tools-reel-capacity-v1';let current=0;let state={};
const ids=['referenceSize','referenceLength','targetSize','targetLength','backingSize'];
function selected(name){return form.querySelector(`input[name="${name}"]:checked`)?.value||''}
function syncState(){state.mode=selected('mode')||state.mode;state.basis=selected('basis')||state.basis;ids.forEach(id=>state[id]=document.querySelector(`#${id}`).value);localStorage.setItem(storageKey,JSON.stringify(state))}
function restore(){try{state=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{state={}};['mode','basis'].forEach(name=>{const input=form.querySelector(`input[name="${name}"][value="${state[name]}"]`);if(input)input.checked=true});ids.forEach(id=>{if(state[id]!==undefined)document.querySelector(`#${id}`).value=state[id]})}
function updateLabels(){const diameter=state.basis==='diameter';const unit=diameter?'mm':'号';document.querySelector('#referenceSizeLabel').textContent=diameter?'基準ライン直径':'基準PE号数';document.querySelector('#referenceSizeUnit').textContent=unit;document.querySelector('#targetSizeLabel').textContent=diameter?'巻きたいライン直径':'巻きたいPE号数';document.querySelector('#targetSizeUnit').textContent=unit;document.querySelector('#backingSizeLabel').textContent=diameter?'下巻きライン直径':'下巻きPE号数';document.querySelector('#backingSizeUnit').textContent=unit;document.querySelector('#referenceExample').textContent=diameter?'例：直径0.18mm・150mなら「0.18」「150」':'例：PE1号・200mなら「1」「200」';document.querySelectorAll('.backing-only').forEach(x=>x.hidden=state.mode!=='backing');document.querySelector('#lineStepTitle').textContent=state.mode==='backing'?'上糸と下巻きを入力':'巻きたいラインを入力';}
function showStep(index,focusHeading=true){current=index;steps.forEach((s,i)=>s.hidden=i!==index);progress.style.width=`${((index+1)/steps.length)*100}%`;progressLabel.textContent=`${index+1} / ${steps.length}`;error.textContent='';if(focusHeading)steps[index].querySelector('legend')?.focus?.()}
function validateStep(){syncState();if(current===0&&!state.mode)return'調べたい内容を1つ選んでください。';if(current===1&&!state.basis)return'計算に使う表示を1つ選んでください。';const sizeType=state.basis==='diameter'?'diameter':'pe';if(current===2)return validateNumber(state.referenceSize,sizeType,state.basis==='diameter'?'基準ライン直径':'基準PE号数')||validateNumber(state.referenceLength,'length','基準糸巻き量');if(current===3){let message=validateNumber(state.targetSize,sizeType,state.basis==='diameter'?'巻きたいライン直径':'巻きたいPE号数');if(!message&&state.mode==='backing')message=validateNumber(state.targetLength,'length','上糸の長さ')||validateNumber(state.backingSize,sizeType,state.basis==='diameter'?'下巻きライン直径':'下巻きPE号数');return message}return''}
function lineText(size){return state.basis==='diameter'?`直径${size}mm`:`PE${size}号`}
function accuracyHtml(precision){return precision==='higher'?'<strong>目安精度：高め</strong><span>メーカー記載のライン直径を使った体積比の計算です。</span>':'<strong>目安精度：標準</strong><span>同じ種類のPEライン同士を号数で換算しています。</span>'}
function render(){syncState();const input={basis:state.basis,referenceSize:state.referenceSize,referenceLength:state.referenceLength,targetSize:state.targetSize,targetLength:state.targetLength,backingSize:state.backingSize};const r=state.mode==='capacity'?calculateCapacity(input):calculateBacking(input);const answerLabel=document.querySelector('#answerLabel');const answerMain=document.querySelector('#answerMain');const answerSub=document.querySelector('#answerSub');const title=document.querySelector('#resultTitle');const flow=document.querySelector('#conditionFlow');const formula=document.querySelector('#formulaText');if(state.mode==='capacity'){title.textContent='巻ける糸巻き量の目安';answerLabel.textContent=`${lineText(state.targetSize)}なら`;answerMain.textContent=`約${roundMeters(r.length)}m`;answerSub.textContent='このリールに巻ける総量の目安';flow.innerHTML=`<div><span>リール表記</span><strong>${lineText(state.referenceSize)}・${state.referenceLength}m</strong></div><b>↓</b><div><span>巻きたいライン</span><strong>${lineText(state.targetSize)}</strong></div>`;formula.textContent=state.basis==='pe'?`${state.referenceSize}号 × ${state.referenceLength}m ÷ ${state.targetSize}号 = 約${roundMeters(r.length)}m`:`${state.referenceSize}mm² × ${state.referenceLength}m ÷ ${state.targetSize}mm² = 約${roundMeters(r.length)}m`;}else{title.textContent=r.status==='over'?'スプール容量を超えています':r.status==='none'?'下巻きは不要です':'おすすめの下巻き量';answerLabel.textContent=r.status==='ok'?lineText(state.backingSize):'今回の条件';answerMain.textContent=r.status==='ok'?`約${roundMeters(r.backingLength)}m`:r.status==='none'?'下巻き 0m':`上糸は約${roundMeters(r.maximumTopLength)}mまで`;answerSub.textContent=r.status==='over'?'指定した上糸をすべて巻く容量がありません':r.status==='none'?'上糸だけで計算上の容量に達します':'下巻きとして先に巻く長さの目安';flow.innerHTML=`<div><span>リール表記</span><strong>${lineText(state.referenceSize)}・${state.referenceLength}m</strong></div><b>＋</b><div><span>上糸</span><strong>${lineText(state.targetSize)}・${state.targetLength}m</strong></div><b>＋</b><div><span>下巻き</span><strong>${lineText(state.backingSize)}</strong></div>`;const factor=state.basis==='diameter'?'直径²':'号数';formula.textContent=r.status==='over'?`スプール容量より、上糸が使う量（${factor}×長さ）のほうが大きいため下巻きできません。`:`全容量から上糸が使う量（${factor}×長さ）を引き、残りを下巻きラインの${factor}で割っています。`;}document.querySelector('#accuracy').innerHTML=accuracyHtml(r.precision);document.querySelector('#resultNotice').textContent='実際の糸巻き量は、ライン製品、巻きテンション、巻き偏り、スプールの満巻位置などによって前後します。スプールの目安線とリールの取扱説明書を確認してください。';result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'start'})}
form.addEventListener('change',e=>{syncState();if(e.target.name==='mode'||e.target.name==='basis')updateLabels()});form.addEventListener('input',syncState);form.addEventListener('click',e=>{const next=e.target.closest('[data-next]');const back=e.target.closest('[data-back]');if(next){const message=validateStep();if(message){error.textContent=message;return}if(current<steps.length-1){updateLabels();showStep(current+1)}else render()}if(back&&current>0)showStep(current-1)});document.querySelector('#retry').addEventListener('click',()=>{result.hidden=true;showStep(0);window.scrollTo({top:document.querySelector('.tool-panel').offsetTop-80,behavior:'smooth'})});restore();updateLabels();showStep(0,false);

