import{calculateMixedSpool,NYLON_DIAMETERS,roundMeters,validateNumber}from'./logic.js?v=material-v5';
const form=document.querySelector('#reelForm'),steps=[...form.querySelectorAll('.step')],result=document.querySelector('#result'),error=form.querySelector('.form-error');
const key='fishing-tools-reel-capacity-v5';let current=0,state={};
const ids=['referenceSize','referenceLength','targetSize','targetLength','backingSize'];
const names=['mode','targetMaterial','referenceMaterial'];
const el=id=>document.getElementById(id);
function save(){for(const n of names)state[n]=form.querySelector(`input[name="${n}"]:checked`)?.value||'';for(const id of ids)state[id]=el(id).value;try{localStorage.setItem(key,JSON.stringify(state))}catch{}}
function restore(){try{state=JSON.parse(localStorage.getItem(key)||'{}')}catch{state={}}for(const n of names){const input=form.querySelector(`input[name="${n}"][value="${state[n]}"]`);if(input)input.checked=true}for(const id of ids)if(state[id]!==undefined)el(id).value=state[id]}
const material=m=>m==='nylon'?'ナイロン':'PE';
function labels(){el('referenceSizeLabel').textContent=`リールに書いてある${material(state.referenceMaterial)}号数`;el('targetSizeLabel').textContent=`巻きたい${material(state.targetMaterial)}号数`;el('referenceExample').textContent=state.referenceMaterial==='nylon'?'例：ナイロン2号・150mなら「2」「150」':'例：PE1号・200mなら「1」「200」';form.querySelectorAll('.backing-only').forEach(x=>x.hidden=state.mode!=='backing');el('lineStepTitle').textContent=state.mode==='backing'?'上糸と下巻きを入力':'巻きたいラインを入力';el('lineStepHelp').textContent=state.mode==='backing'?'使いたい上糸の号数・長さと、下巻きのナイロン号数を入力します。':'巻きたいラインの号数を入力します。';}
function show(index,focus=true){current=index;steps.forEach((s,i)=>s.hidden=i!==index);document.querySelector('.progress-label').textContent=`${index+1} / 4`;document.querySelector('.progress-bar').style.width=`${(index+1)*25}%`;error.textContent='';if(focus)steps[index].querySelector('legend').focus()}
function sizeError(value,m,label){const msg=validateNumber(value,'pe',label);if(msg)return msg;if(m==='nylon'&&!NYLON_DIAMETERS[value])return`${label}は1・1.25・1.5・2・2.5・3・3.5・4・4.5・5号から入力してください。`;return''}
function validate(){save();if(current===0)return state.mode?'':'調べたい内容を選んでください。';if(current===1)return !state.targetMaterial?'巻きたいラインを選んでください。':!state.referenceMaterial?'リールに書かれている表記を選んでください。':'';if(current===2)return sizeError(state.referenceSize,state.referenceMaterial,'リール表記の号数')||validateNumber(state.referenceLength,'length','リール表記の糸巻き量');return sizeError(state.targetSize,state.targetMaterial,'巻きたいラインの号数')||(state.mode==='backing'?(validateNumber(state.targetLength,'length','上糸の長さ')||(!NYLON_DIAMETERS[state.backingSize]?'下巻きナイロン号数を選んでください。':'')):'')}
function render(){const r=calculateMixedSpool(state),backing=state.mode==='backing';const ref=`${material(state.referenceMaterial)}${state.referenceSize}号・${state.referenceLength}m`,top=`${material(state.targetMaterial)}${state.targetSize}号`;
 el('resultTitle').textContent=!backing?'巻ける糸巻き量の目安':r.status==='over'?'スプール容量を超えています':r.status==='none'?'下巻きは不要です':'下巻き量の目安';
 el('answerLabel').textContent=!backing?`${top}なら`:r.status==='ok'?`ナイロン${state.backingSize}号`:'今回の条件';
 el('answerMain').textContent=!backing?`約${roundMeters(r.length)}m`:r.status==='over'?`上糸は約${roundMeters(r.maximumTopLength)}mまで`:r.status==='none'?'下巻き 0m':`約${roundMeters(r.backingLength)}m`;
 el('answerSub').textContent=!backing?'このリールに巻ける総量の目安':r.status==='over'?'上糸の長さを減らして再計算してください。':r.status==='none'?'計算上は上糸だけで容量に達します。':'先に巻くナイロンの長さの目安';
 el('conditionFlow').replaceChildren();for(const [label,value] of [['リール表記',ref],['巻きたいライン',top+(backing?`・${state.targetLength}m`:'')],...(backing?[['下巻き',`ナイロン${state.backingSize}号`]]:[])]){const d=document.createElement('div'),s=document.createElement('span'),b=document.createElement('strong');s.textContent=label;b.textContent=value;d.append(s,b);el('conditionFlow').append(d)}
 el('accuracy').innerHTML=r.approximate?'<strong>目安精度：概算（異素材の換算）</strong><span>シマノ公式Q&Aの概算方法を参考にしています。PEの号数を直径とみなす計算ではありません。製品差があるため、実際の巻き量を確認してください。</span>':'<strong>目安精度：標準</strong><span>PEは号数比、ナイロンは標準直径の二乗比で換算しています。製品差や巻き方で前後します。</span>';
 el('formulaText').textContent=r.approximate?'シマノ公式Q&Aの「ナイロンからPEへの巻き換えは号数比で求めた長さ÷1.2」を参考に、PEの容量係数を号数×1.2、ナイロンを号数として概算します。下巻きは全容量から上糸の使用分を引いて求めます。このツールでの逆換算・下巻きへの適用は同じ容量モデルからの推定で、メーカーが各リールで保証する値ではありません。':'同じ種類のPEは号数×長さ、ナイロンは標準直径の二乗×長さを基に換算します。下巻きは上糸が使った分を引いて求めます。';
 el('resultNotice').textContent='実際の糸巻き量はライン製品・巻きテンション・満巻位置で前後します。特に異素材の換算は概算です。目安線と取扱説明書を優先し、最後は実際の巻き量を確認してください。';result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'start'})}
form.addEventListener('change',()=>{save();labels();result.hidden=true});form.addEventListener('input',()=>{save();result.hidden=true});form.addEventListener('click',e=>{if(e.target.closest('[data-next]')){const msg=validate();if(msg){error.textContent=msg;return}labels();if(current===3)render();else show(current+1)}if(e.target.closest('[data-back]')&&current>0)show(current-1)});el('retry').addEventListener('click',()=>{result.hidden=true;show(0);form.scrollIntoView({behavior:'smooth',block:'start'})});restore();labels();show(0,false);
